### ISSUE TITLE
Documentation on Tiling Map 

### ISSUE THREAD

**Issue by stevenanthonyrevo** [pokettomonstaa/NewBark#8]
Great work on this game, just has a quick question! 

Is there anyway we can get more documentation on setting up a map/level? Tiled Map Editor is great but it seems the files only export as .tmx files and are missing the .txs files. Did you hard code the .txs file or was there a different way to generate both the .txs and .tmx files for the map? 

Thanks,
Steve

**Comment by itsjavi** [comment]
hello thank you, do you mean the `.tsx` files? The scene 01 is using overworld.tsx
and all can be found here
https://github.com/pokettomonstaa/NewBark/tree/master/assets/map

**Comment by stevenanthonyrevo** [comment]
Thank you @itsjavi, this makes sense now! 

Looking at it again [Tiled](http://www.mapeditor.org/) has docs on building a map. Sorry I didn't see this before. The external template file `.tsx` is referenced here: http://docs.mapeditor.org/en/latest/reference/tmx-map-format/#tmx-object 

Thanks
